/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaanproject;

/**
 *
 * @author oscar
 */
public class Halaman_utama extends javax.swing.JFrame {

    /**
     * Creates new form Halaman_utama
     */
    public Halaman_utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlpha1 = new perpustakaanproject.PanelAlpha();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelAlpha2 = new perpustakaanproject.PanelAlpha();
        Keluar = new javax.swing.JButton();
        panelAlpha3 = new perpustakaanproject.PanelAlpha();
        panelAlpha4 = new perpustakaanproject.PanelAlpha();
        Data_anggota = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelAlpha5 = new perpustakaanproject.PanelAlpha();
        Laporan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelAlpha6 = new perpustakaanproject.PanelAlpha();
        Data_peminjaman = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        panelAlpha7 = new perpustakaanproject.PanelAlpha();
        jLabel5 = new javax.swing.JLabel();
        Data_buku = new javax.swing.JButton();
        panelAlpha8 = new perpustakaanproject.PanelAlpha();
        Data_pengembalian = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAlpha1.setBackground(new java.awt.Color(153, 255, 153));
        panelAlpha1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PERPUSTAKAAN");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SMA Budhi Warman 1 Jakarta Timur");

        javax.swing.GroupLayout panelAlpha1Layout = new javax.swing.GroupLayout(panelAlpha1);
        panelAlpha1.setLayout(panelAlpha1Layout);
        panelAlpha1Layout.setHorizontalGroup(
            panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha1Layout.createSequentialGroup()
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha1Layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jLabel2))
                    .addGroup(panelAlpha1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel3)))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        panelAlpha1Layout.setVerticalGroup(
            panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(panelAlpha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        panelAlpha2.setBackground(new java.awt.Color(153, 255, 153));
        panelAlpha2.setOpaque(false);

        Keluar.setBackground(new java.awt.Color(255, 255, 255));
        Keluar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icon_close-removebg-preview.png"))); // NOI18N
        Keluar.setText("KELUAR");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlpha2Layout = new javax.swing.GroupLayout(panelAlpha2);
        panelAlpha2.setLayout(panelAlpha2Layout);
        panelAlpha2Layout.setHorizontalGroup(
            panelAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Keluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        panelAlpha2Layout.setVerticalGroup(
            panelAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelAlpha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1000, 70));

        panelAlpha3.setOpaque(false);

        panelAlpha4.setBackground(new java.awt.Color(153, 153, 255));
        panelAlpha4.setOpaque(false);

        Data_anggota.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Data_anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Data anggota.png"))); // NOI18N
        Data_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_anggotaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("DATA ANGGOTA");

        javax.swing.GroupLayout panelAlpha4Layout = new javax.swing.GroupLayout(panelAlpha4);
        panelAlpha4.setLayout(panelAlpha4Layout);
        panelAlpha4Layout.setHorizontalGroup(
            panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(Data_anggota))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelAlpha4Layout.setVerticalGroup(
            panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Data_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAlpha5.setBackground(new java.awt.Color(153, 153, 255));
        panelAlpha5.setOpaque(false);

        Laporan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icon_laporan_1-removebg-preview.png"))); // NOI18N
        Laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("LAPORAN");

        javax.swing.GroupLayout panelAlpha5Layout = new javax.swing.GroupLayout(panelAlpha5);
        panelAlpha5.setLayout(panelAlpha5Layout);
        panelAlpha5Layout.setHorizontalGroup(
            panelAlpha5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelAlpha5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel8)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panelAlpha5Layout.setVerticalGroup(
            panelAlpha5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        panelAlpha6.setBackground(new java.awt.Color(153, 153, 255));
        panelAlpha6.setOpaque(false);

        Data_peminjaman.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Data_peminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Peminjaman buku.png"))); // NOI18N
        Data_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_peminjamanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("DATA PEMINJAMAN");

        javax.swing.GroupLayout panelAlpha6Layout = new javax.swing.GroupLayout(panelAlpha6);
        panelAlpha6.setLayout(panelAlpha6Layout);
        panelAlpha6Layout.setHorizontalGroup(
            panelAlpha6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelAlpha6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(Data_peminjaman))
                .addGap(20, 20, 20))
        );
        panelAlpha6Layout.setVerticalGroup(
            panelAlpha6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Data_peminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(37, 37, 37))
        );

        panelAlpha7.setBackground(new java.awt.Color(153, 153, 255));
        panelAlpha7.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("DATA BUKU");

        Data_buku.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Data_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Data buku.png"))); // NOI18N
        Data_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_bukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlpha7Layout = new javax.swing.GroupLayout(panelAlpha7);
        panelAlpha7.setLayout(panelAlpha7Layout);
        panelAlpha7Layout.setHorizontalGroup(
            panelAlpha7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha7Layout.createSequentialGroup()
                .addGroup(panelAlpha7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Data_buku))
                    .addGroup(panelAlpha7Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelAlpha7Layout.setVerticalGroup(
            panelAlpha7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Data_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(28, 28, 28))
        );

        panelAlpha8.setBackground(new java.awt.Color(153, 153, 255));
        panelAlpha8.setOpaque(false);

        Data_pengembalian.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Data_pengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Pengembalian buku.png"))); // NOI18N
        Data_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_pengembalianActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("DATA PENGEMBALIAN");

        javax.swing.GroupLayout panelAlpha8Layout = new javax.swing.GroupLayout(panelAlpha8);
        panelAlpha8.setLayout(panelAlpha8Layout);
        panelAlpha8Layout.setHorizontalGroup(
            panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha8Layout.createSequentialGroup()
                .addGroup(panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(panelAlpha8Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Data_pengembalian)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlpha8Layout.setVerticalGroup(
            panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Data_pengembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAlpha3Layout = new javax.swing.GroupLayout(panelAlpha3);
        panelAlpha3.setLayout(panelAlpha3Layout);
        panelAlpha3Layout.setHorizontalGroup(
            panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(panelAlpha8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(panelAlpha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(panelAlpha7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(panelAlpha6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(panelAlpha3Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(panelAlpha5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlpha3Layout.setVerticalGroup(
            panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(panelAlpha7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelAlpha3Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(panelAlpha6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addComponent(panelAlpha4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelAlpha8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(21, 21, 21)
                .addComponent(panelAlpha5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(panelAlpha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1000, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Menu Utama.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1015, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Data_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_anggotaActionPerformed
        // TODO add your handling code here:
        new Data_anggota().setVisible(true);
        dispose();
    }//GEN-LAST:event_Data_anggotaActionPerformed

    private void Data_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_bukuActionPerformed
        // TODO add your handling code here:
        new Data_buku().setVisible(true);
        dispose();
    }//GEN-LAST:event_Data_bukuActionPerformed

    private void Data_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_peminjamanActionPerformed
        // TODO add your handling code here:
        new Peminjaman_buku().setVisible(true);
        dispose();
    }//GEN-LAST:event_Data_peminjamanActionPerformed

    private void Data_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_pengembalianActionPerformed
        // TODO add your handling code here:
        new Pengembalian_buku().setVisible(true);
        dispose();
    }//GEN-LAST:event_Data_pengembalianActionPerformed

    private void LaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanActionPerformed
        // TODO add your handling code here:
        new Laporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_LaporanActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        new Login ().setVisible(true);
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Data_anggota;
    private javax.swing.JButton Data_buku;
    private javax.swing.JButton Data_peminjaman;
    private javax.swing.JButton Data_pengembalian;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Laporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private perpustakaanproject.PanelAlpha panelAlpha1;
    private perpustakaanproject.PanelAlpha panelAlpha2;
    private perpustakaanproject.PanelAlpha panelAlpha3;
    private perpustakaanproject.PanelAlpha panelAlpha4;
    private perpustakaanproject.PanelAlpha panelAlpha5;
    private perpustakaanproject.PanelAlpha panelAlpha6;
    private perpustakaanproject.PanelAlpha panelAlpha7;
    private perpustakaanproject.PanelAlpha panelAlpha8;
    // End of variables declaration//GEN-END:variables
}
