/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaanproject;
import java.sql.Connection;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import Koneksi.Database;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author oscar
 */
public class Laporan extends javax.swing.JFrame {
private Connection conn = new Database().connect();
private DefaultTableModel tabmode;
    
    public Laporan() {
        initComponents();
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlpha1 = new perpustakaanproject.PanelAlpha();
        panelAlpha2 = new perpustakaanproject.PanelAlpha();
        jLabel2 = new javax.swing.JLabel();
        tanggal = new javax.swing.JSpinner();
        panelAlpha8 = new perpustakaanproject.PanelAlpha();
        Data_pengembalian = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelAlpha4 = new perpustakaanproject.PanelAlpha();
        Data_anggota = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelAlpha7 = new perpustakaanproject.PanelAlpha();
        jLabel5 = new javax.swing.JLabel();
        Data_buku = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panelAlpha6 = new perpustakaanproject.PanelAlpha();
        Data_peminjaman = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAlpha1.setOpaque(false);

        panelAlpha2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("LAPORAN");

        javax.swing.GroupLayout panelAlpha2Layout = new javax.swing.GroupLayout(panelAlpha2);
        panelAlpha2.setLayout(panelAlpha2Layout);
        panelAlpha2Layout.setHorizontalGroup(
            panelAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28))
        );
        panelAlpha2Layout.setVerticalGroup(
            panelAlpha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tanggal.setModel(new javax.swing.SpinnerDateModel());

        panelAlpha8.setBackground(new java.awt.Color(153, 255, 255));
        panelAlpha8.setOpaque(false);

        Data_pengembalian.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Data_pengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Pengembalian buku.png"))); // NOI18N
        Data_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_pengembalianActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("DATA PENGEMBALIAN");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("CETAK");

        javax.swing.GroupLayout panelAlpha8Layout = new javax.swing.GroupLayout(panelAlpha8);
        panelAlpha8.setLayout(panelAlpha8Layout);
        panelAlpha8Layout.setHorizontalGroup(
            panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha8Layout.createSequentialGroup()
                .addGroup(panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(panelAlpha8Layout.createSequentialGroup()
                        .addGroup(panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAlpha8Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Data_pengembalian))
                            .addGroup(panelAlpha8Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAlpha8Layout.setVerticalGroup(
            panelAlpha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Data_pengembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        panelAlpha4.setBackground(new java.awt.Color(153, 255, 255));
        panelAlpha4.setOpaque(false);

        Data_anggota.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Data_anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Data anggota.png"))); // NOI18N
        Data_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_anggotaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("DATA ANGGOTA");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("CETAK");

        javax.swing.GroupLayout panelAlpha4Layout = new javax.swing.GroupLayout(panelAlpha4);
        panelAlpha4.setLayout(panelAlpha4Layout);
        panelAlpha4Layout.setHorizontalGroup(
            panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(28, 28, 28))
            .addGroup(panelAlpha4Layout.createSequentialGroup()
                .addGroup(panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Data_anggota))
                    .addGroup(panelAlpha4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel8)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelAlpha4Layout.setVerticalGroup(
            panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Data_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        panelAlpha7.setBackground(new java.awt.Color(153, 255, 255));
        panelAlpha7.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("DATA BUKU");

        Data_buku.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Data_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Data buku.png"))); // NOI18N
        Data_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_bukuActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("CETAK");

        javax.swing.GroupLayout panelAlpha7Layout = new javax.swing.GroupLayout(panelAlpha7);
        panelAlpha7.setLayout(panelAlpha7Layout);
        panelAlpha7Layout.setHorizontalGroup(
            panelAlpha7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Data_buku)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAlpha7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40))))
        );
        panelAlpha7Layout.setVerticalGroup(
            panelAlpha7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Data_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        panelAlpha6.setBackground(new java.awt.Color(153, 255, 255));
        panelAlpha6.setOpaque(false);

        Data_peminjaman.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Data_peminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Peminjaman buku.png"))); // NOI18N
        Data_peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_peminjamanActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("DATA PEMINJAMAN");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("CETAK");

        javax.swing.GroupLayout panelAlpha6Layout = new javax.swing.GroupLayout(panelAlpha6);
        panelAlpha6.setLayout(panelAlpha6Layout);
        panelAlpha6Layout.setHorizontalGroup(
            panelAlpha6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha6Layout.createSequentialGroup()
                .addGroup(panelAlpha6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelAlpha6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Data_peminjaman)))
                    .addGroup(panelAlpha6Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel10)))
                .addGap(20, 20, 20))
        );
        panelAlpha6Layout.setVerticalGroup(
            panelAlpha6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Data_peminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        Kembali.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlpha1Layout = new javax.swing.GroupLayout(panelAlpha1);
        panelAlpha1.setLayout(panelAlpha1Layout);
        panelAlpha1Layout.setHorizontalGroup(
            panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha1Layout.createSequentialGroup()
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(panelAlpha8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(panelAlpha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(panelAlpha7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(panelAlpha6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAlpha1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Kembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelAlpha2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        panelAlpha1Layout.setVerticalGroup(
            panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlpha1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAlpha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelAlpha6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelAlpha7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAlpha4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAlpha8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(207, 207, 207))
        );

        getContentPane().add(panelAlpha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/background form.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1265, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Data_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_pengembalianActionPerformed
        // TODO add your handling code here:
        try {
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\PerpustakaanProject\\src\\Laporan\\Pengembalian.jasper";
            HashMap parameter = new HashMap();
            //parameter.put("no",txtno.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_Data_pengembalianActionPerformed

    private void Data_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_anggotaActionPerformed
        // TODO add your handling code here:
         try {
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\PerpustakaanProject\\src\\Laporan\\Dataanggota.jasper";
            HashMap parameter = new HashMap();
            //parameter.put("no",txtno.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_Data_anggotaActionPerformed

    private void Data_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_bukuActionPerformed
        // TODO add your handling code here:
         try {
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\PerpustakaanProject\\src\\Laporan\\Databuku.jasper";
            HashMap parameter = new HashMap();
            //parameter.put("no",txtno.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_Data_bukuActionPerformed

    private void Data_peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_peminjamanActionPerformed
        // TODO add your handling code here:
        try {
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\PerpustakaanProject\\src\\Laporan\\Peminjaman.jasper";
            HashMap parameter = new HashMap();
            //parameter.put("no",txtno.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_Data_peminjamanActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        Halaman_utama Pp = new Halaman_utama();
        Pp.setVisible(true);
        Pp.setResizable(false);
        dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Data_anggota;
    private javax.swing.JButton Data_buku;
    private javax.swing.JButton Data_peminjaman;
    private javax.swing.JButton Data_pengembalian;
    private javax.swing.JButton Kembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private perpustakaanproject.PanelAlpha panelAlpha1;
    private perpustakaanproject.PanelAlpha panelAlpha2;
    private perpustakaanproject.PanelAlpha panelAlpha4;
    private perpustakaanproject.PanelAlpha panelAlpha6;
    private perpustakaanproject.PanelAlpha panelAlpha7;
    private perpustakaanproject.PanelAlpha panelAlpha8;
    private javax.swing.JSpinner tanggal;
    // End of variables declaration//GEN-END:variables
}
