/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaanproject;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Koneksi.Database;
import Popup.popuppeminjaman;
import Popup.popuppengembalian;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author oscar
 */
public class Pengembalian_buku extends javax.swing.JFrame {
public String nomorpinjam,tgl_kembali,nomorbuku,judulbuku,nomoranggota,namaanggota,jmlahpinjam;
public String nomorkembali;
  private Connection conn = new Database().connect();
private DefaultTableModel tabmode;
 
Object[] Baris ={"Nomor Peminjaman","Nomor Buku","Judul Buku","Nomor Anggota","Nama Anggota","Jumlah Pinjaman","Tanggal Pengembalian","Tanggal Sekarang","Lama Peminjaman","Denda","Nominal Di bayarkan","Sisa Uang","Keterangan"};

    public Pengembalian_buku() {
        initComponents();
        kosong();
        aktif();
        autonumber();
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);    
        tabmode = new DefaultTableModel(null, Baris);
    }

    protected void kosong(){
no_kembali.setText("");
no_buku.setText("");
jdl_buku.setText("");
no_ang.setText("");
nama_ang.setText("");
jmlpinjam.setText("");
no_pinjam.setText("");
tglkembali.setText("");
tglsekarang.setCalendar(null);
lama_pinjam.setText("");
denda.setText("");
di_bayar.setText("");
sisa.setText("");
ket1.setText("");
//Table.removeAll();
    }
    
    protected void aktif(){
lama_pinjam.requestFocus();
no_kembali.setEnabled(false);  
Ubah.setEnabled(false); 
}
    
    protected void autonumber(){
 try{
 String sql = "SELECT No_pengembalian FROM data_pengembalian order by No_pengembalian asc";
 Statement stat = conn.createStatement();
 ResultSet rs=stat.executeQuery(sql);

 while(rs.next()){
 String No_pengembalian = rs.getString("No_pengembalian").substring(2);
 int nomor = Integer.parseInt(No_pengembalian) + 1;
 String nol = "";

 if (nomor<10)
 {nol = "000";}
 else if (nomor<100)
 {nol = "00";}
 else if (nomor<1000)
 {nol = "";}

 no_kembali.setText("KE" + nol + nomor);
 }
 }
 catch (Exception e){
      JOptionPane.showMessageDialog(null,"Penomoran Salah" + e);
 }
}
    
    public void removeTable(){
    try{
         for(int t=tabmode.getRowCount();t>0;t--) {tabmode.removeRow(0);}    }
    catch(Exception ex){ System.out.println(ex);  } }


     public void popuppeminjaman(){
     popuppeminjaman Pp = new popuppeminjaman();
     Pp.pinjam1 = this;
     no_pinjam.setText(nomorpinjam);
     tglkembali.setText(tgl_kembali);
     no_buku.setText(nomorbuku);
     jdl_buku.setText(judulbuku);
     no_ang.setText(nomoranggota);
     nama_ang.setText(namaanggota);
     jmlpinjam.setText(jmlahpinjam);
 }
     
     public void popuppengembalian(){
     popuppengembalian Pp = new popuppengembalian();
     Pp.kembali = this;
     cetak.setText(nomorkembali);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlpha1 = new perpustakaanproject.PanelAlpha();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        no_kembali = new javax.swing.JTextField();
        no_buku = new javax.swing.JTextField();
        jdl_buku = new javax.swing.JTextField();
        panelAlpha4 = new perpustakaanproject.PanelAlpha();
        jLabel7 = new javax.swing.JLabel();
        no_ang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama_ang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        no_pinjam = new javax.swing.JTextField();
        Cari_pinjam = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jmlpinjam = new javax.swing.JTextField();
        panelAlpha3 = new perpustakaanproject.PanelAlpha();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tglsekarang = new com.toedter.calendar.JDateChooser();
        lama_pinjam = new javax.swing.JTextField();
        denda = new javax.swing.JTextField();
        tglkembali = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        di_bayar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        sisa = new javax.swing.JTextField();
        Bayar = new javax.swing.JButton();
        hari = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ket = new javax.swing.JComboBox<>();
        ket1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cetak = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Tambah = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        Batal = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Ubah = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAlpha1.setBackground(new java.awt.Color(255, 255, 153));
        panelAlpha1.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nomor Buku");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Judul Buku");

        no_kembali.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        no_buku.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        no_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_bukuActionPerformed(evt);
            }
        });

        jdl_buku.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jdl_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdl_bukuActionPerformed(evt);
            }
        });

        panelAlpha4.setBackground(new java.awt.Color(153, 255, 153));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("PENGEMBALIAN BUKU");

        javax.swing.GroupLayout panelAlpha4Layout = new javax.swing.GroupLayout(panelAlpha4);
        panelAlpha4.setLayout(panelAlpha4Layout);
        panelAlpha4Layout.setHorizontalGroup(
            panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelAlpha4Layout.setVerticalGroup(
            panelAlpha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        no_ang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("No Anggota");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Nama Anggota");

        nama_ang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nama_ang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_angActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("No Peminjaman");

        no_pinjam.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        Cari_pinjam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cari_pinjam.setText("Cari");
        Cari_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cari_pinjamActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Jumlah Pinjaman");

        jmlpinjam.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelAlpha1Layout = new javax.swing.GroupLayout(panelAlpha1);
        panelAlpha1.setLayout(panelAlpha1Layout);
        panelAlpha1Layout.setHorizontalGroup(
            panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha1Layout.createSequentialGroup()
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAlpha1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addGroup(panelAlpha1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel6))))
                        .addGap(79, 79, 79)
                        .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAlpha1Layout.createSequentialGroup()
                                .addComponent(no_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cari_pinjam))
                            .addComponent(jdl_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no_ang, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jmlpinjam, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nama_ang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAlpha1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelAlpha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(no_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAlpha1Layout.setVerticalGroup(
            panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(no_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAlpha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cari_pinjam)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(no_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jdl_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(no_ang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(nama_ang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jmlpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelAlpha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 380));

        panelAlpha3.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Tanggal Sekarang");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Lama Peminjaman");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Denda");

        lama_pinjam.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lama_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lama_pinjamActionPerformed(evt);
            }
        });

        denda.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tglkembali.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Tanggal pengembalian");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Nominal Dibayarkan");

        di_bayar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Sisa Uang");

        sisa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        Bayar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Bayar.setText("BAYAR");
        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });

        hari.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Hari ", "2 Hari ", "3 Hari ", "4 Hari ", "5 Hari ", "6 Hari ", "7 Hari ", "8 Hari ", "9 Hari ", "10 Hari ", "11 Hari ", "12 Hari ", "13 Hari ", "14 Hari ", "15 Hari ", "16 Hari ", "17 Hari ", "18 Hari", "19 Hari ", "20 Hari  ", " " }));
        hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hariActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Keterangan");

        ket.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Tidak Lunas" }));
        ket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketActionPerformed(evt);
            }
        });

        ket1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ket1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons-hand.png"))); // NOI18N
        jButton2.setText("Cari Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cetak.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons-print.png"))); // NOI18N
        jButton1.setText("CETAK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlpha3Layout = new javax.swing.GroupLayout(panelAlpha3);
        panelAlpha3.setLayout(panelAlpha3Layout);
        panelAlpha3Layout.setHorizontalGroup(
            panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha3Layout.createSequentialGroup()
                        .addComponent(di_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bayar))
                    .addGroup(panelAlpha3Layout.createSequentialGroup()
                        .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sisa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAlpha3Layout.createSequentialGroup()
                                    .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ket1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(denda)
                        .addComponent(tglsekarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tglkembali)
                        .addGroup(panelAlpha3Layout.createSequentialGroup()
                            .addComponent(hari, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lama_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        panelAlpha3Layout.setVerticalGroup(
            panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlpha3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tglsekarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lama_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(denda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlpha3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel13))
                    .addGroup(panelAlpha3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(di_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bayar))))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(sisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panelAlpha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        getContentPane().add(panelAlpha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 660, 380));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1250, 140));

        Tambah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons-plus.png"))); // NOI18N
        Tambah.setText("TAMBAH");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        getContentPane().add(Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 390, -1, -1));

        Kembali.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons-back.png"))); // NOI18N
        Kembali.setText("KEMBALI");
        Kembali.setToolTipText("");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, -1, -1));

        Batal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons-cancel.png"))); // NOI18N
        Batal.setText("BATAL");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });
        getContentPane().add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        Hapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons-delete.png"))); // NOI18N
        Hapus.setText("HAPUS");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        Ubah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons-edit.png"))); // NOI18N
        Ubah.setText("UBAH");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });
        getContentPane().add(Ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        Simpan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-save-30.png"))); // NOI18N
        Simpan.setText("SIMPAN");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/background form.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1266, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lama_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lama_pinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lama_pinjamActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        

        String zsql = "insert into data_pengembalian values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
            int t = Table.getRowCount();
            for(int i=0; i < t ; i++)
            {
                
                String No_pinjaman = Table.getValueAt(i, 0).toString();
                String Nomor_buku = Table.getValueAt(i, 1).toString();
                String Judul_buku = Table.getValueAt(i, 2).toString();
                String Nomor_anggota = Table.getValueAt(i, 3).toString();
                String Nama_anggota = Table.getValueAt(i, 4).toString();
                String Jumlah_Pinjam = Table.getValueAt(i, 5).toString();
                String Tanggal_pengembalian = Table.getValueAt(i, 6).toString();
                String Tanggal_sekarang = Table.getValueAt(i, 7).toString();
                String Lama_peminjaman = Table.getValueAt(i, 8).toString();
                String Denda = Table.getValueAt(i, 9).toString();
                String Di_bayarkan = Table.getValueAt(i, 10).toString();
                String Sisa_Uang = Table.getValueAt(i, 11).toString();
                String Keterangan = Table.getValueAt(i, 12).toString();

                PreparedStatement stat2 = conn.prepareStatement(zsql);
                stat2.setString(1, no_kembali.getText());
                stat2.setString(2, No_pinjaman);
                stat2.setString(3, Nomor_buku);
                stat2.setString(4, Judul_buku);
                stat2.setString(5, Nomor_anggota);
                stat2.setString(6, Nama_anggota);
                stat2.setString(7, Jumlah_Pinjam);
                stat2.setString(8, Tanggal_pengembalian);
                stat2.setString(9, Tanggal_sekarang);
                stat2.setString(10, Lama_peminjaman);
                stat2.setString(11, Denda);
                stat2.setString(12, Di_bayarkan);
                stat2.setString(13, Sisa_Uang);
                stat2.setString(14, Keterangan);
                stat2.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        }catch(Exception e)
        {
            System.out.println("Error : "+e);
        }
        kosong();
        autonumber();
        removeTable();
                                                                    

    }//GEN-LAST:event_SimpanActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
String sekarang = sdf.format(tglsekarang.getDate());
        try{
            String nopinj = no_pinjam.getText();
            String nobuk = no_buku.getText();
            String jdlbuk = jdl_buku.getText();
            String noang = no_ang.getText();
            String namaang = nama_ang.getText();
            String jmlpinj = jmlpinjam.getText();
            String kembalibuku = tglkembali.getText();
            String pinjam_buku = sekarang;
            String lama = lama_pinjam.getText();
            String Denda = denda.getText();
            String dibayar = di_bayar.getText();
            String sisauang = sisa.getText();
            String keterangan = ket1.getText();
            
            
            
            tabmode.addRow(new Object[]{nopinj,nobuk,jdlbuk,noang,namaang,jmlpinj,kembalibuku,pinjam_buku,lama,Denda,dibayar,sisauang,keterangan});
            Table.setModel(tabmode);
        }
        catch(Exception e)
        {
            System.out.println("Error : "+e);
        }
       
        no_pinjam.setText("");
        no_buku.setText("");
        jdl_buku.setText("");
        no_ang.setText("");
        nama_ang.setText("");
        jmlpinjam.setText("");
        tglkembali.setText("");
        tglsekarang.setCalendar(null);
        lama_pinjam.setText("");
        denda.setText("");
        di_bayar.setText("");
        sisa.setText("");
        ket1.setText("");
            
    }//GEN-LAST:event_TambahActionPerformed

    private void Cari_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cari_pinjamActionPerformed
        // TODO add your handling code here:
        popuppeminjaman Pp = new popuppeminjaman();
        Pp.pinjam1 = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_Cari_pinjamActionPerformed

    private void no_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_bukuActionPerformed

    private void nama_angActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_angActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_angActionPerformed

    private void jdl_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdl_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jdl_bukuActionPerformed

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
        // TODO add your handling code here:
         int bp,bk,sisa1;
       bp=Integer.parseInt(denda.getText());
       bk=Integer.parseInt(di_bayar.getText());     
       sisa1=bk-bp;
       sisa.setText(String.valueOf(sisa1));
    }//GEN-LAST:event_BayarActionPerformed

    private void ketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketActionPerformed
        // TODO add your handling code here:
        String text;
        text = (String)ket.getSelectedItem();
        ket1.setText(text);
    }//GEN-LAST:event_ketActionPerformed

    private void hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hariActionPerformed
        // TODO add your handling code here:
        String text;
        text = (String)hari.getSelectedItem();
        lama_pinjam.setText(text);
    }//GEN-LAST:event_hariActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
          int br=Table.getSelectedRow();
        String a=Table.getValueAt(br,0).toString();
        String b=Table.getValueAt(br,1).toString();
        String c=Table.getValueAt(br,2).toString();
        String d=Table.getValueAt(br,3).toString();
        String e=Table.getValueAt(br,4).toString();
        String f=Table.getValueAt(br,5).toString();
        String g=Table.getValueAt(br,6).toString();
        String h=Table.getValueAt(br,7).toString();
        String i=Table.getValueAt(br,8).toString();
        String j=Table.getValueAt(br,9).toString();
        String k=Table.getValueAt(br,10).toString();
        String l=Table.getValueAt(br,11).toString();
        String m=Table.getValueAt(br,12).toString();
   
        no_pinjam.setText(a);
        no_buku.setText(b);
        jdl_buku.setText(c);
        no_ang.setText(d);
        nama_ang.setText(e);
        jmlpinjam.setText(f);
        tglkembali.setText(g);
        tglsekarang.setDateFormatString(h);
        lama_pinjam.setText(i);
        denda.setText(j);
        di_bayar.setText(k);
        sisa.setText(l);
        ket1.setText(m);
    }//GEN-LAST:event_TableMouseClicked

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
         Halaman_utama Pp = new Halaman_utama();
        Pp.setVisible(true);
        Pp.setResizable(false);
        dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
        // TODO add your handling code here:
        kosong();
        autonumber();
    }//GEN-LAST:event_BatalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String path="C:\\Users\\oscar\\Documents\\NetBeansProjects\\PerpustakaanProject\\src\\Laporan\\Notapembayarandenda.jasper";
            HashMap parameter = new HashMap();
            parameter.put("nama",cetak.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ket1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ket1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        popuppengembalian Pp = new popuppengembalian();
        Pp.kembali = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusActionPerformed

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian_buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JButton Bayar;
    private javax.swing.JButton Cari_pinjam;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable Table;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Ubah;
    private javax.swing.JTextField cetak;
    private javax.swing.JTextField denda;
    private javax.swing.JTextField di_bayar;
    private javax.swing.JComboBox<String> hari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jdl_buku;
    private javax.swing.JTextField jmlpinjam;
    private javax.swing.JComboBox<String> ket;
    private javax.swing.JTextField ket1;
    private javax.swing.JTextField lama_pinjam;
    private javax.swing.JTextField nama_ang;
    private javax.swing.JTextField no_ang;
    private javax.swing.JTextField no_buku;
    private javax.swing.JTextField no_kembali;
    private javax.swing.JTextField no_pinjam;
    private perpustakaanproject.PanelAlpha panelAlpha1;
    private perpustakaanproject.PanelAlpha panelAlpha3;
    private perpustakaanproject.PanelAlpha panelAlpha4;
    private javax.swing.JTextField sisa;
    private javax.swing.JTextField tglkembali;
    private com.toedter.calendar.JDateChooser tglsekarang;
    // End of variables declaration//GEN-END:variables
}
